name: CI - Lint and Format

on:
  push:
    branches:
      - master
      - develop

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format
      - name: Check for formatting changes
        run: git diff --exit-code
        if: success()
      - name: Run ESLint
        run: npm run lint
