name: Docker Security Audit

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  docker-security:
    name: Docker Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Enable Docker Content Trust
        run: echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/discord-notifier:21-alpine3.18 .

      - name: Install Dockle
        run: |
          wget https://github.com/goodwithtech/dockle/releases/download/v0.4.14/dockle_0.4.14_Linux-64bit.deb
          sudo dpkg -i dockle_0.4.14_Linux-64bit.deb

      - name: Run Dockle
        run: dockle --exit-code 1 ${{ secrets.DOCKER_USERNAME }}/discord-notifier:21-alpine3.18
